// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: mtn/csv.proto

package mtn

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CsvFileOptions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CsvFileOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CsvFileOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CsvFileOptionsMultiError,
// or nil if none found.
func (m *CsvFileOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *CsvFileOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Header

	// no validation rules for Comma

	// no validation rules for Encoding

	// no validation rules for QuoteMinimally

	if len(errors) > 0 {
		return CsvFileOptionsMultiError(errors)
	}

	return nil
}

// CsvFileOptionsMultiError is an error wrapping multiple validation errors
// returned by CsvFileOptions.ValidateAll() if the designated constraints
// aren't met.
type CsvFileOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CsvFileOptionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CsvFileOptionsMultiError) AllErrors() []error { return m }

// CsvFileOptionsValidationError is the validation error returned by
// CsvFileOptions.Validate if the designated constraints aren't met.
type CsvFileOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CsvFileOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CsvFileOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CsvFileOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CsvFileOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CsvFileOptionsValidationError) ErrorName() string { return "CsvFileOptionsValidationError" }

// Error satisfies the builtin error interface
func (e CsvFileOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCsvFileOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CsvFileOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CsvFileOptionsValidationError{}

// Validate checks the field values on CsvColumnOptions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CsvColumnOptions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CsvColumnOptions with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CsvColumnOptionsMultiError, or nil if none found.
func (m *CsvColumnOptions) ValidateAll() error {
	return m.validate(true)
}

func (m *CsvColumnOptions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Column

	// no validation rules for Header

	// no validation rules for Default

	if len(errors) > 0 {
		return CsvColumnOptionsMultiError(errors)
	}

	return nil
}

// CsvColumnOptionsMultiError is an error wrapping multiple validation errors
// returned by CsvColumnOptions.ValidateAll() if the designated constraints
// aren't met.
type CsvColumnOptionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CsvColumnOptionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CsvColumnOptionsMultiError) AllErrors() []error { return m }

// CsvColumnOptionsValidationError is the validation error returned by
// CsvColumnOptions.Validate if the designated constraints aren't met.
type CsvColumnOptionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CsvColumnOptionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CsvColumnOptionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CsvColumnOptionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CsvColumnOptionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CsvColumnOptionsValidationError) ErrorName() string { return "CsvColumnOptionsValidationError" }

// Error satisfies the builtin error interface
func (e CsvColumnOptionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCsvColumnOptions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CsvColumnOptionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CsvColumnOptionsValidationError{}
