// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: survey_io.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// required targets
type ExportSurveyResultFilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required survey_base_request_id
	// required status_code
	Targets []*ExportSurveyResultFilesRequest_Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// 出力済みを対象に含める
	IncludeExported bool `protobuf:"varint,2,opt,name=include_exported,json=includeExported,proto3" json:"include_exported,omitempty"`
}

func (x *ExportSurveyResultFilesRequest) Reset() {
	*x = ExportSurveyResultFilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_survey_io_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportSurveyResultFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSurveyResultFilesRequest) ProtoMessage() {}

func (x *ExportSurveyResultFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_io_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSurveyResultFilesRequest.ProtoReflect.Descriptor instead.
func (*ExportSurveyResultFilesRequest) Descriptor() ([]byte, []int) {
	return file_survey_io_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSurveyResultFilesRequest) GetTargets() []*ExportSurveyResultFilesRequest_Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ExportSurveyResultFilesRequest) GetIncludeExported() bool {
	if x != nil {
		return x.IncludeExported
	}
	return false
}

type ExportSurveyResultFilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
}

func (x *ExportSurveyResultFilesResponse) Reset() {
	*x = ExportSurveyResultFilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_survey_io_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportSurveyResultFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSurveyResultFilesResponse) ProtoMessage() {}

func (x *ExportSurveyResultFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_survey_io_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSurveyResultFilesResponse.ProtoReflect.Descriptor instead.
func (*ExportSurveyResultFilesResponse) Descriptor() ([]byte, []int) {
	return file_survey_io_proto_rawDescGZIP(), []int{1}
}

func (x *ExportSurveyResultFilesResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type ExportSurveyResultFilesRequest_Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SurveyBaseRequestId string `protobuf:"bytes,1,opt,name=survey_base_request_id,json=surveyBaseRequestId,proto3" json:"survey_base_request_id,omitempty"`
	StatusCode          string `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *ExportSurveyResultFilesRequest_Target) Reset() {
	*x = ExportSurveyResultFilesRequest_Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_survey_io_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportSurveyResultFilesRequest_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSurveyResultFilesRequest_Target) ProtoMessage() {}

func (x *ExportSurveyResultFilesRequest_Target) ProtoReflect() protoreflect.Message {
	mi := &file_survey_io_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSurveyResultFilesRequest_Target.ProtoReflect.Descriptor instead.
func (*ExportSurveyResultFilesRequest_Target) Descriptor() ([]byte, []int) {
	return file_survey_io_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ExportSurveyResultFilesRequest_Target) GetSurveyBaseRequestId() string {
	if x != nil {
		return x.SurveyBaseRequestId
	}
	return ""
}

func (x *ExportSurveyResultFilesRequest_Target) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

var File_survey_io_proto protoreflect.FileDescriptor

var file_survey_io_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x5f, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x6d, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x61, 0x76, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x22, 0x82, 0x02, 0x0a, 0x1e, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x55, 0x0a, 0x07, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6d, 0x74,
	0x65, 0x63, 0x68, 0x6e, 0x61, 0x76, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x75, 0x72, 0x76,
	0x65, 0x79, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x65, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x6e, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x1a, 0x5e, 0x0a, 0x06,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3c, 0x0a, 0x1f,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x32, 0x9a, 0x01, 0x0a, 0x0f, 0x53,
	0x75, 0x72, 0x76, 0x65, 0x79, 0x49, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x86,
	0x01, 0x0a, 0x17, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x34, 0x2e, 0x6d, 0x74, 0x65,
	0x63, 0x68, 0x6e, 0x61, 0x76, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x75, 0x72, 0x76, 0x65,
	0x79, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x72, 0x76, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x35, 0x2e, 0x6d, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x61, 0x76, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75,
	0x72, 0x76, 0x65, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x6d, 0x74, 0x65, 0x63, 0x68,
	0x6e, 0x61, 0x76, 0x69, 0x2f, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_survey_io_proto_rawDescOnce sync.Once
	file_survey_io_proto_rawDescData = file_survey_io_proto_rawDesc
)

func file_survey_io_proto_rawDescGZIP() []byte {
	file_survey_io_proto_rawDescOnce.Do(func() {
		file_survey_io_proto_rawDescData = protoimpl.X.CompressGZIP(file_survey_io_proto_rawDescData)
	})
	return file_survey_io_proto_rawDescData
}

var file_survey_io_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_survey_io_proto_goTypes = []interface{}{
	(*ExportSurveyResultFilesRequest)(nil),        // 0: mtechnavi.api.survey.ExportSurveyResultFilesRequest
	(*ExportSurveyResultFilesResponse)(nil),       // 1: mtechnavi.api.survey.ExportSurveyResultFilesResponse
	(*ExportSurveyResultFilesRequest_Target)(nil), // 2: mtechnavi.api.survey.ExportSurveyResultFilesRequest.Target
}
var file_survey_io_proto_depIdxs = []int32{
	2, // 0: mtechnavi.api.survey.ExportSurveyResultFilesRequest.targets:type_name -> mtechnavi.api.survey.ExportSurveyResultFilesRequest.Target
	0, // 1: mtechnavi.api.survey.SurveyIOService.ExportSurveyResultFiles:input_type -> mtechnavi.api.survey.ExportSurveyResultFilesRequest
	1, // 2: mtechnavi.api.survey.SurveyIOService.ExportSurveyResultFiles:output_type -> mtechnavi.api.survey.ExportSurveyResultFilesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_survey_io_proto_init() }
func file_survey_io_proto_init() {
	if File_survey_io_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_survey_io_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportSurveyResultFilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_survey_io_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportSurveyResultFilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_survey_io_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportSurveyResultFilesRequest_Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_survey_io_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_survey_io_proto_goTypes,
		DependencyIndexes: file_survey_io_proto_depIdxs,
		MessageInfos:      file_survey_io_proto_msgTypes,
	}.Build()
	File_survey_io_proto = out.File
	file_survey_io_proto_rawDesc = nil
	file_survey_io_proto_goTypes = nil
	file_survey_io_proto_depIdxs = nil
}
