// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: surveyrequestcatalog.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SurveyRequestCatalog with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SurveyRequestCatalog) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SurveyRequestCatalog with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SurveyRequestCatalogMultiError, or nil if none found.
func (m *SurveyRequestCatalog) ValidateAll() error {
	return m.validate(true)
}

func (m *SurveyRequestCatalog) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SurveyRequestCatalogId

	// no validation rules for Code

	// no validation rules for DisplayName

	if all {
		switch v := interface{}(m.GetCategory()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SurveyRequestCatalogValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SurveyRequestCatalogValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategory()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SurveyRequestCatalogValidationError{
				field:  "Category",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Guidance

	// no validation rules for Approval

	if all {
		switch v := interface{}(m.GetCompleteCondition()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SurveyRequestCatalogValidationError{
					field:  "CompleteCondition",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SurveyRequestCatalogValidationError{
					field:  "CompleteCondition",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompleteCondition()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SurveyRequestCatalogValidationError{
				field:  "CompleteCondition",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PartialReply

	// no validation rules for Decline

	for idx, item := range m.GetAutoReminderSettings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SurveyRequestCatalogValidationError{
						field:  fmt.Sprintf("AutoReminderSettings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SurveyRequestCatalogValidationError{
						field:  fmt.Sprintf("AutoReminderSettings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SurveyRequestCatalogValidationError{
					field:  fmt.Sprintf("AutoReminderSettings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetCommonAttachments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SurveyRequestCatalogValidationError{
						field:  fmt.Sprintf("CommonAttachments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SurveyRequestCatalogValidationError{
						field:  fmt.Sprintf("CommonAttachments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SurveyRequestCatalogValidationError{
					field:  fmt.Sprintf("CommonAttachments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for SurveyRequestCatalogUpdatedAt

	if all {
		switch v := interface{}(m.GetSurveyRequestCatalogUpdatedBy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SurveyRequestCatalogValidationError{
					field:  "SurveyRequestCatalogUpdatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SurveyRequestCatalogValidationError{
					field:  "SurveyRequestCatalogUpdatedBy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSurveyRequestCatalogUpdatedBy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SurveyRequestCatalogValidationError{
				field:  "SurveyRequestCatalogUpdatedBy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for DeletedAt

	if len(errors) > 0 {
		return SurveyRequestCatalogMultiError(errors)
	}

	return nil
}

// SurveyRequestCatalogMultiError is an error wrapping multiple validation
// errors returned by SurveyRequestCatalog.ValidateAll() if the designated
// constraints aren't met.
type SurveyRequestCatalogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SurveyRequestCatalogMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SurveyRequestCatalogMultiError) AllErrors() []error { return m }

// SurveyRequestCatalogValidationError is the validation error returned by
// SurveyRequestCatalog.Validate if the designated constraints aren't met.
type SurveyRequestCatalogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SurveyRequestCatalogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SurveyRequestCatalogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SurveyRequestCatalogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SurveyRequestCatalogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SurveyRequestCatalogValidationError) ErrorName() string {
	return "SurveyRequestCatalogValidationError"
}

// Error satisfies the builtin error interface
func (e SurveyRequestCatalogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSurveyRequestCatalog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SurveyRequestCatalogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SurveyRequestCatalogValidationError{}
