// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: batch.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ScheduleJobDailyMailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ScheduleJobDailyMailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScheduleJobDailyMailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScheduleJobDailyMailRequestMultiError, or nil if none found.
func (m *ScheduleJobDailyMailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ScheduleJobDailyMailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Since

	// no validation rules for Until

	if len(errors) > 0 {
		return ScheduleJobDailyMailRequestMultiError(errors)
	}

	return nil
}

// ScheduleJobDailyMailRequestMultiError is an error wrapping multiple
// validation errors returned by ScheduleJobDailyMailRequest.ValidateAll() if
// the designated constraints aren't met.
type ScheduleJobDailyMailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScheduleJobDailyMailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScheduleJobDailyMailRequestMultiError) AllErrors() []error { return m }

// ScheduleJobDailyMailRequestValidationError is the validation error returned
// by ScheduleJobDailyMailRequest.Validate if the designated constraints
// aren't met.
type ScheduleJobDailyMailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScheduleJobDailyMailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScheduleJobDailyMailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScheduleJobDailyMailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScheduleJobDailyMailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScheduleJobDailyMailRequestValidationError) ErrorName() string {
	return "ScheduleJobDailyMailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ScheduleJobDailyMailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScheduleJobDailyMailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScheduleJobDailyMailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScheduleJobDailyMailRequestValidationError{}

// Validate checks the field values on ScheduleJobSharetoSurveyReminderRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ScheduleJobSharetoSurveyReminderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ScheduleJobSharetoSurveyReminderRequest with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// ScheduleJobSharetoSurveyReminderRequestMultiError, or nil if none found.
func (m *ScheduleJobSharetoSurveyReminderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ScheduleJobSharetoSurveyReminderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ScheduleJobSharetoSurveyReminderRequestMultiError(errors)
	}

	return nil
}

// ScheduleJobSharetoSurveyReminderRequestMultiError is an error wrapping
// multiple validation errors returned by
// ScheduleJobSharetoSurveyReminderRequest.ValidateAll() if the designated
// constraints aren't met.
type ScheduleJobSharetoSurveyReminderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScheduleJobSharetoSurveyReminderRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScheduleJobSharetoSurveyReminderRequestMultiError) AllErrors() []error { return m }

// ScheduleJobSharetoSurveyReminderRequestValidationError is the validation
// error returned by ScheduleJobSharetoSurveyReminderRequest.Validate if the
// designated constraints aren't met.
type ScheduleJobSharetoSurveyReminderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScheduleJobSharetoSurveyReminderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScheduleJobSharetoSurveyReminderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScheduleJobSharetoSurveyReminderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScheduleJobSharetoSurveyReminderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScheduleJobSharetoSurveyReminderRequestValidationError) ErrorName() string {
	return "ScheduleJobSharetoSurveyReminderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ScheduleJobSharetoSurveyReminderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScheduleJobSharetoSurveyReminderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScheduleJobSharetoSurveyReminderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScheduleJobSharetoSurveyReminderRequestValidationError{}

// Validate checks the field values on
// ScheduleJobSharetoBusinessUnitManagementRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ScheduleJobSharetoBusinessUnitManagementRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ScheduleJobSharetoBusinessUnitManagementRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in
// ScheduleJobSharetoBusinessUnitManagementRequestMultiError, or nil if none found.
func (m *ScheduleJobSharetoBusinessUnitManagementRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ScheduleJobSharetoBusinessUnitManagementRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ScheduleJobSharetoBusinessUnitManagementRequestMultiError(errors)
	}

	return nil
}

// ScheduleJobSharetoBusinessUnitManagementRequestMultiError is an error
// wrapping multiple validation errors returned by
// ScheduleJobSharetoBusinessUnitManagementRequest.ValidateAll() if the
// designated constraints aren't met.
type ScheduleJobSharetoBusinessUnitManagementRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScheduleJobSharetoBusinessUnitManagementRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScheduleJobSharetoBusinessUnitManagementRequestMultiError) AllErrors() []error { return m }

// ScheduleJobSharetoBusinessUnitManagementRequestValidationError is the
// validation error returned by
// ScheduleJobSharetoBusinessUnitManagementRequest.Validate if the designated
// constraints aren't met.
type ScheduleJobSharetoBusinessUnitManagementRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScheduleJobSharetoBusinessUnitManagementRequestValidationError) Field() string {
	return e.field
}

// Reason function returns reason value.
func (e ScheduleJobSharetoBusinessUnitManagementRequestValidationError) Reason() string {
	return e.reason
}

// Cause function returns cause value.
func (e ScheduleJobSharetoBusinessUnitManagementRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScheduleJobSharetoBusinessUnitManagementRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScheduleJobSharetoBusinessUnitManagementRequestValidationError) ErrorName() string {
	return "ScheduleJobSharetoBusinessUnitManagementRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ScheduleJobSharetoBusinessUnitManagementRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScheduleJobSharetoBusinessUnitManagementRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScheduleJobSharetoBusinessUnitManagementRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScheduleJobSharetoBusinessUnitManagementRequestValidationError{}
