// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: worktaskrelation.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on WorkTaskRelation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WorkTaskRelation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkTaskRelation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WorkTaskRelationMultiError, or nil if none found.
func (m *WorkTaskRelation) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkTaskRelation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkTaskRelationId

	// no validation rules for LinkedWorkTaskId

	// no validation rules for Urn

	// no validation rules for TypeName

	// no validation rules for RecordId

	if all {
		switch v := interface{}(m.GetSystemCategory()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkTaskRelationValidationError{
					field:  "SystemCategory",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkTaskRelationValidationError{
					field:  "SystemCategory",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSystemCategory()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkTaskRelationValidationError{
				field:  "SystemCategory",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for DeletedAt

	if len(errors) > 0 {
		return WorkTaskRelationMultiError(errors)
	}

	return nil
}

// WorkTaskRelationMultiError is an error wrapping multiple validation errors
// returned by WorkTaskRelation.ValidateAll() if the designated constraints
// aren't met.
type WorkTaskRelationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkTaskRelationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkTaskRelationMultiError) AllErrors() []error { return m }

// WorkTaskRelationValidationError is the validation error returned by
// WorkTaskRelation.Validate if the designated constraints aren't met.
type WorkTaskRelationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkTaskRelationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkTaskRelationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkTaskRelationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkTaskRelationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkTaskRelationValidationError) ErrorName() string { return "WorkTaskRelationValidationError" }

// Error satisfies the builtin error interface
func (e WorkTaskRelationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkTaskRelation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkTaskRelationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkTaskRelationValidationError{}

// Validate checks the field values on WorkTaskRelationContent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WorkTaskRelationContent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkTaskRelationContent with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WorkTaskRelationContentMultiError, or nil if none found.
func (m *WorkTaskRelationContent) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkTaskRelationContent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetWorkTaskRelation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkTaskRelationContentValidationError{
					field:  "WorkTaskRelation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkTaskRelationContentValidationError{
					field:  "WorkTaskRelation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWorkTaskRelation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkTaskRelationContentValidationError{
				field:  "WorkTaskRelation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Code

	// no validation rules for DisplayName

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkTaskRelationContentValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkTaskRelationContentValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkTaskRelationContentValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WorkTaskRelationContentMultiError(errors)
	}

	return nil
}

// WorkTaskRelationContentMultiError is an error wrapping multiple validation
// errors returned by WorkTaskRelationContent.ValidateAll() if the designated
// constraints aren't met.
type WorkTaskRelationContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkTaskRelationContentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkTaskRelationContentMultiError) AllErrors() []error { return m }

// WorkTaskRelationContentValidationError is the validation error returned by
// WorkTaskRelationContent.Validate if the designated constraints aren't met.
type WorkTaskRelationContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkTaskRelationContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkTaskRelationContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkTaskRelationContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkTaskRelationContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkTaskRelationContentValidationError) ErrorName() string {
	return "WorkTaskRelationContentValidationError"
}

// Error satisfies the builtin error interface
func (e WorkTaskRelationContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkTaskRelationContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkTaskRelationContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkTaskRelationContentValidationError{}
