// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: notificationsetting.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通知内容
type NotificationSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// システム名
	SystemCategory string `protobuf:"bytes,1,opt,name=system_category,json=systemCategory,proto3" json:"system_category,omitempty"`
	// タイトル名
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// URL遷移先
	Link string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	// TOs
	Tos []string `protobuf:"bytes,5,rep,name=tos,proto3" json:"tos,omitempty"`
	// CCs
	Ccs []string `protobuf:"bytes,6,rep,name=ccs,proto3" json:"ccs,omitempty"`
	// 通知元
	// 企業名を格納する
	SenderTenant string `protobuf:"bytes,7,opt,name=sender_tenant,json=senderTenant,proto3" json:"sender_tenant,omitempty"`
}

func (x *NotificationSetting) Reset() {
	*x = NotificationSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notificationsetting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSetting) ProtoMessage() {}

func (x *NotificationSetting) ProtoReflect() protoreflect.Message {
	mi := &file_notificationsetting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSetting.ProtoReflect.Descriptor instead.
func (*NotificationSetting) Descriptor() ([]byte, []int) {
	return file_notificationsetting_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationSetting) GetSystemCategory() string {
	if x != nil {
		return x.SystemCategory
	}
	return ""
}

func (x *NotificationSetting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationSetting) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationSetting) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *NotificationSetting) GetTos() []string {
	if x != nil {
		return x.Tos
	}
	return nil
}

func (x *NotificationSetting) GetCcs() []string {
	if x != nil {
		return x.Ccs
	}
	return nil
}

func (x *NotificationSetting) GetSenderTenant() string {
	if x != nil {
		return x.SenderTenant
	}
	return ""
}

var File_notificationsetting_proto protoreflect.FileDescriptor

var file_notificationsetting_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x6c, 0x69, 0x62, 0x22, 0xcb, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a,
	0x0f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x63, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x63, 0x63, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x61, 0x76, 0x69,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notificationsetting_proto_rawDescOnce sync.Once
	file_notificationsetting_proto_rawDescData = file_notificationsetting_proto_rawDesc
)

func file_notificationsetting_proto_rawDescGZIP() []byte {
	file_notificationsetting_proto_rawDescOnce.Do(func() {
		file_notificationsetting_proto_rawDescData = protoimpl.X.CompressGZIP(file_notificationsetting_proto_rawDescData)
	})
	return file_notificationsetting_proto_rawDescData
}

var file_notificationsetting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notificationsetting_proto_goTypes = []interface{}{
	(*NotificationSetting)(nil), // 0: sharelib.NotificationSetting
}
var file_notificationsetting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificationsetting_proto_init() }
func file_notificationsetting_proto_init() {
	if File_notificationsetting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notificationsetting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificationSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notificationsetting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notificationsetting_proto_goTypes,
		DependencyIndexes: file_notificationsetting_proto_depIdxs,
		MessageInfos:      file_notificationsetting_proto_msgTypes,
	}.Build()
	File_notificationsetting_proto = out.File
	file_notificationsetting_proto_rawDesc = nil
	file_notificationsetting_proto_goTypes = nil
	file_notificationsetting_proto_depIdxs = nil
}
